apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app: vprodb
  type: ClusterIP
  ports:
  - name: mysqldb-cluster
    port:  3306
    targetPort: vprodb-port
    protocol: TCP